server:
  port: 9999

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: bill-service
          uri: http://localhost:8080
          predicates:
            - Path=/bills
        - id: passenger-service
          uri: http://localhost:8081
          predicates:
            - Path=/passengers/**